<?php
    /**
     * greatjob.to
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to john@jo.mu so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY\GreatJob
     * @copyright Copyright (c) 2018 John Mullanaphy (https://jo.mu/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy <john@jo.mu>
     *
     * @var $this \PHY\View\Block
     * @var $name string
     * @var $id int
     */
?>
<div class="fixed-bottom container-fluid bg-dark py-3">
  <div class="row">
    <div class="col-9 col-md-4 mr-auto">
      <form id="generate" class="form">
        <div class="input-group">
          <input id="generate-input" aria-describedby="generate-input-label" type="text" class="form-control"
                 data-toggle="popover" data-placement="top" data-content="Please enter a name!" value=""
                 placeholder="Hey (First Name)!">
          <div class="input-group-append">
            <button id="generate-input" type="submit" class="btn btn-primary btn-outline">&#128075;&#128075;</button>
          </div>
        </div>
      </form>
    </div>
    <div class="col-3 col-md-5 ml-auto">
      <div class="input-group">
        <div class="input-group-prepend d-none d-md-inline">
          <span class="input-group-text">Share:</span>
        </div>
        <input id="url" type="text" class="d-none d-md-inline form-control"
               value="https://&#128075;&#128075;.to/<?= $this->clean($name) ?>"
               data-toggle="popover" data-placement="top" data-content="Copied!">
        <button class="btn btn-danger ml-2" data-toggle="modal" data-target="#modal-report" id="modal-report-opener">
          Report
        </button>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="modal-report" tabindex="-1" role="dialog" aria-labelledby="modal-report-opener"
     aria-hidden="true">
  <form action="<?= $this->url('reserved/report') ?>" method="post" id="model-report-form">
    <input type="hidden" name="id" id="modal-report-id" value="<?= (int)$id ?>">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="modal-report-title">Report? Fiddlesticks!</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Sorry you have to report this name. We believe in no bummers. Thanks for helping keep this site clean!</p>
          <p>Oh, both fields are optional.</p>
          <div class="form-group">
            <label for="modal-report-email">Email:</label>
            <input type="email" class="form-control" id="modal-report-email" placeholder="name@example.com">
          </div>
          <div class="form-group">
            <label for="modal-report-comment">Comments:</label>
            <textarea class="form-control" id="modal-report-comment" rows="3"
                      placeholder="Please give some reasoning"></textarea>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-danger">Report</button>
        </div>
      </div>
    </div>
  </form>
</div>
<div class="modal fade" id="modal-report-thanks" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-report-title">Reported!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Thank you for reporting this page, if you provided an email address I will try and keep you up to date!</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-success" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<script src="<?= $this->url('report.js', 'js') ?>"></script>