<?php
    /**
     * greatjob.to
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to john@jo.mu so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY\GreatJob
     * @copyright Copyright (c) 2018 John Mullanaphy (https://jo.mu/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy <john@jo.mu>
     *
     * @var $this \PHY\View\Block
     * @var $name string
     * @var $count int
     */
?>
<div class="jumbotron">
  <div class="container text-center">
    <h1 class="display-4">Great Job! <strong><?= $this->clean($name) ?></strong> &#128075;&#128075;</h1>
    <p class="lead">Someone thinks you're doing swell!</p>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col text-center">
      <img class="img-fluid" src="<?= $this->url('greatjob-1.gif', 'image') ?>">
    </div>
  </div>
</div>
<div class="fixed-bottom container-fluid bg-dark py-3">
  <div class="row">
    <div class="col-md-7">
      <form id="generate" class="form-inline">
        <div class="input-group">
          <input id="generate-input" aria-describedby="generate-input-label" type="text" class="form-control"
                 data-toggle="popover" data-placement="top" data-content="Please enter a name!" value=""
                 placeholder="Hey (First Name)!">
          <div class="input-group-append">
            <button id="generate-input" type="submit" class="btn btn-primary btn-outline">&#128075;&#128075;</button>
          </div>
        </div>
      </form>
    </div>
    <div class="col-md-5 justify-content-end">
      <div class="input-group">
        <div class="input-group-prepend">
          <span class="input-group-text">Share:</span>
        </div>
        <input id="url" type="text" class="form-control"
               value="https://&#128075;&#128075;.to/<?= $this->clean($name) ?>"
               data-toggle="popover" data-placement="top" data-content="Copied!">
        <button class="btn btn-danger ml-2" data-toggle="modal" data-target="#modal-report" id="modal-report-opener">
          Report
        </button>
      </div>
    </div>
  </div>
</div>
