<?php
    /**
     * greatjob.to
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to hi@john.mu so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY\GreatJob
     * @copyright Copyright (c) 2018 John Mullanaphy (https://john.mu/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy <hi@john.mu>
     *
     * @var $this \PHY\View\Block
     * @var $name string
     * @var $count int
     */
?>
<div class="jumbotron">
  <div class="container text-center">
    <h1 class="display-4">Great Job <strong><?= $this->clean($name) ?></strong>! &#128075;&#128075;</h1>
    <p class="lead">Someone thinks you're doing swell!</p>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col text-center">
      <img class="img-fluid" src="<?= $this->url('greatjob-1.gif', 'image') ?>">
    </div>
  </div>
</div>
