<?php
    /**
     * greatjob.to
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to john@jo.mu so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY\GreatJob
     * @copyright Copyright (c) 2018 John Mullanaphy (https://jo.mu/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy <john@jo.mu>
     *
     * @var $this \PHY\View\Block
     * @var $name string
     * @var $count int
     */
?>
<div class="container">
  <div class="row">
    <div class="col text-center">
      <form id="generate" class="form-inline">
        <div class="input-group">
          <input id="generate-input" aria-describedby="generate-input-label" type="text" class="form-control"
                 data-toggle="popover" data-placement="top" data-content="Please enter a name!" value=""
                 placeholder="Hey (First Name)!">
          <div class="input-group-append">
            <button id="generate-input" type="submit" class="btn btn-primary btn-outline">&#128075;&#128075;</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
<script src="<?= $this->url('report.js', 'js') ?>"></script>
