<?php
    /**
     * greatjob.to
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to john@jo.mu so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY\GreatJob
     * @copyright Copyright (c) 2018 John Mullanaphy (https://jo.mu/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy <john@jo.mu>
     *
     * @var $this \PHY\View\Block
     * @var $name string
     * @var $count int
     */
?>
<div class="jumbotron">
  <div class="container text-center">
    <h1 class="display-4"><strong>Great Job! &#128075;&#128075;</strong></h1>
    <p class="lead">Let somebody know they did a great job:</p>
    <form id="generate" class="col-12 col-lg-4 mx-auto">
      <div class="input-group">
        <input id="generate-input" aria-describedby="generate-input-label" type="text" class="form-control"
               data-toggle="popover" data-placement="top" data-content="Please enter a name!" value=""
               placeholder="Hey (First Name)!">
        <div class="input-group-append">
          <button id="generate-input" type="submit" class="btn btn-primary btn-outline">&#128075;&#128075;</button>
        </div>
      </div>
    </form>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-12 col-lg-4 mx-auto">
      <h3>Heads up!</h3>
      <p>We like to keep this site void of all bummers. You can curse yet nothing hateful. In essence, please follow the
        <strong><a href="https://mbmbam.wikia.com/wiki/Episode_234:_The_Legend_of_Cracker_Barrel"
                   rel="nofollow">Obama midnight amendments</a></strong>:</p>
      <ol>
        <li>Be Cool</li>
        <li>C'mon</li>
        <li>Niice</li>
      </ol>
    </div>
  </div>
</div>
<div class="fixed-bottom text-muted text-center p-1">
  <small>Created by <a href="https://jo.mu">John Mullanaphy</a> as a solo project without outside endorsements. <a
        href="https://github.com/mullanaphy/greatjob.to"><i class="fab fa-github-alt"></i>
      Source Code</a></small>
</div>
